#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ft=python
import datetime

weekdays = ('月','火','水','木','金','土','日')
def convert_with_time(t):
    return t.strftime('%m/%d(A) %H:%M〜').replace('A', weekdays[t.weekday()])

def convert(t):
    return t.strftime('%m/%d(A)').replace('A', weekdays[t.weekday()])

t = datetime.date.today()
d = []

for i in range(60):
    if t.weekday() == 5 or t.weekday() == 6: # 週末
        d.append(convert(t) + ' 10:00〜')
        d.append(convert(t) + ' 14:00〜')
    elif t.weekday() != 0 and t.weekday() != 2 and t.weekday() != 4: # 月水金以外
        d.append(convert(t) + ' 18:00〜')
    t = t + datetime.timedelta(days=1)

for i in range(len(d)):
    print(d[i])
