#!/bin/bash
# vim: set ft=sh

function pdfmin()
{
  gs -sDEVICE=pdfwrite \
              -dCompatibilityLevel=1.4 \
              -dPDFSETTINGS=/ebook \
              -dNOPAUSE -dQUIET -dBATCH \
              -sOutputFile=${i%%.*}.min.pdf ${i} &
}
